### ISSUE TITLE
Roadmap "Logistic Company"

### ISSUE THREAD

**Issue by Alldrich** [Alldrich/LogisticAPI#4]
# Overview
We must cover this functionality
## Features
- [ ] 1. User registration and login
- [ ] 2. Ability to assign roles to users (employee, customer)
- [ ] 3. Entering, displaying, editing and deleting data for:
  - [ ] Logistic company
  - [ ] Company employee
  - [ ] A customer of a company
  - [ ] Company office
  - [ ] Shipment
- [ ] 4. Company employees must be able to log sent and received 
shipments
- [ ] 5. Information in PDF format about:
  - [ ] All employees in the company
  - [ ] All customers of the company
  - [ ] All shipments that have been registered
  - [ ] All shipments that are registered by an employee
  - [ ] All shipments that have been sent but not received
  - [ ] All shipments that are sent by a customer
  - [ ] All shipments that are received from a customer
  - [ ] All revenues of the company for a certain period of time
- [ ] 6. Every employee can see all shipments
- [ ] 7. Each customer can see the shipments they have sent or received

## TO-DO
- [ ] Create unit-tests
